packages:
  - "packages/*"
  - "fixtures/*"
  - "tools"

catalog:
  vitest: ~2.1.3
  "@vitest/runner": ~2.1.3
  "@vitest/snapshot": ~2.1.3
  "@vitest/ui": ~2.1.3
  typescript: "^5.6.3"
  undici: "^5.28.4"
  "@types/node": "^18.19.59"
  ws: "^8.18.0"
  eslint: "^8.57.1"
